/**
 * @file    comm.c
 * @brief   USB CDC serial communication – DeskMixer wire protocol.
 *
 * ── How to hook this up ──────────────────────────────────────────────────
 *
 * 1.  In STM32CubeIDE / CubeMX, enable: Middleware → USB_DEVICE → CDC
 *     then re-generate code.  This creates:
 *       USB_DEVICE/App/usbd_cdc_if.c
 *       USB_DEVICE/App/usbd_cdc_if.h
 *
 * 2.  In usbd_cdc_if.c, locate CDC_Receive_FS() and add one call:
 *       static int8_t CDC_Receive_FS(uint8_t* Buf, uint32_t *Len)
 *       {
 *           COMM_OnRxData(Buf, *Len);            // ← add this line
 *           USBD_CDC_SetRxBuffer(&hUsbDeviceFS, &Buf[0]);
 *           USBD_CDC_ReceivePacket(&hUsbDeviceFS);
 *           return (USBD_OK);
 *       }
 *
 * 3.  Add #include "comm.h" at the top of usbd_cdc_if.c.
 *
 * 4.  comm.c calls CDC_Transmit_FS() which is already declared in
 *     usbd_cdc_if.h – so the linker just needs that object in the build.
 *
 * ────────────────────────────────────────────────────────────────────────
 *
 * If USB CDC middleware is NOT yet set up, this file still compiles:
 * the weak stub at the bottom provides a no-op CDC_Transmit_FS so the
 * project builds without the middleware for iterative development.
 * Remove the stub once real USB CDC is wired in.
 */

#include "comm.h"
#include "sliders.h"   /* NUM_SLIDERS */
#include "buttons.h"   /* NUM_BUTTONS */
#include <string.h>
#include <stdio.h>
#include <stdint.h>

/* ── CDC_Transmit_FS forward declaration ─────────────────────────────── */
/*
 * Defined in USB_DEVICE/App/usbd_cdc_if.c (generated by CubeMX).
 * Declared here so comm.c can call it without pulling in the full USB headers.
 */
extern uint8_t CDC_Transmit_FS(uint8_t *Buf, uint16_t Len);

/* ── Protocol strings ────────────────────────────────────────────────── */
#define HANDSHAKE_REQUEST   "DeskMixer controller request"
#define HANDSHAKE_RESPONSE  "DeskMixer Controller Ready\r\n"

#define NUM_SCREENS         1   /* SCREEN_ACTIVE = 1, matching ESP32 firmware */

/* Helper macro to stringify a numeric define – must be defined BEFORE use */
#define _STR(x) #x
#define STRINGIFY(x) _STR(x)

/* CONFIG string: "CONFIG:SLIDERS:5:BUTTONS:6:SCREEN:1\r\n" */
static const char CONFIG_RESPONSE[] =
    "CONFIG:SLIDERS:" STRINGIFY(NUM_SLIDERS)
    ":BUTTONS:"       STRINGIFY(NUM_BUTTONS)
    ":SCREEN:"        STRINGIFY(NUM_SCREENS) "\r\n";

/* ── RX ring buffer ──────────────────────────────────────────────────── */
static char     s_rxBuf[COMM_RX_BUF_SIZE];
static uint16_t s_rxHead = 0;

/* ── Publicc functions ────────────────────────────────────────────────── */

void COMM_Init(void)
{
    memset(s_rxBuf, 0, sizeof(s_rxBuf));
    s_rxHead = 0;

    /*
     * Send handshake on startup.
     * The Python host listens for this on connect.
     * The USB stack may not be fully enumerated yet – retry a few times.
     */
    for (int attempt = 0; attempt < 5; attempt++) {
        uint8_t result = CDC_Transmit_FS(
            (uint8_t *)HANDSHAKE_RESPONSE,
            (uint16_t)(sizeof(HANDSHAKE_RESPONSE) - 1));
        if (result == 0 /* USBD_OK */) break;
        for (volatile int d = 0; d < 100000; d++) { /* ~10 ms spin */ }
    }
}

void COMM_OnRxData(const uint8_t *buf, uint32_t len)
{
    /*
     * Accumulate incoming bytes into s_rxBuf.
     * When a '\n' (or '\r') is received, attempt to process the line.
     */
    for (uint32_t i = 0; i < len; i++) {
        char c = (char)buf[i];

        if (c == '\r') continue;  /* Ignore CR, wait for LF */

        if (c == '\n') {
            /* Null-terminate and process */
            s_rxBuf[s_rxHead] = '\0';

            if (strcmp(s_rxBuf, HANDSHAKE_REQUEST) == 0) {
                COMM_Send(HANDSHAKE_RESPONSE);
            } else if (strcmp(s_rxBuf, "GET_CONFIG") == 0) {
                COMM_Send(CONFIG_RESPONSE);
            }
            /* Unknown commands are silently ignored (future extension point) */

            s_rxHead = 0;
        } else {
            /* Append character – guard against buffer overflow */
            if (s_rxHead < COMM_RX_BUF_SIZE - 1) {
                s_rxBuf[s_rxHead++] = c;
            } else {
                /* Buffer overflow – discard the corrupted line */
                s_rxHead = 0;
            }
        }
    }
}

void COMM_SendSliders(const uint16_t *values, uint8_t count)
{
    /*
     * Build: "Slider 1 512|Slider 2 1023|...|Slider 5 0\r\n"
     * Max line length: 9 sliders × (8 + 4) chars + 2 = ~110 chars – fits
     * comfortably in COMM_TX_BUF_SIZE (256).
     */
    char buf[COMM_TX_BUF_SIZE];
    int  pos = 0;

    for (uint8_t i = 0; i < count && pos < (int)sizeof(buf) - 16; i++) {
        if (i > 0) buf[pos++] = '|';
        pos += snprintf(buf + pos, sizeof(buf) - pos,
                        "Slider %d %d", i + 1, (int)values[i]);
    }
    buf[pos++] = '\r';
    buf[pos++] = '\n';
    buf[pos]   = '\0';

    COMM_Send(buf);
}

void COMM_SendButtonPress(uint8_t index)
{
    char buf[24];
    int len = snprintf(buf, sizeof(buf), "Button %d 1\r\n", index + 1);
    CDC_Transmit_FS((uint8_t *)buf, (uint16_t)len);
}

void COMM_Send(const char *str)
{
    uint16_t len = (uint16_t)strlen(str);
    if (len == 0) return;

    /*
     * CDC_Transmit_FS returns USBD_BUSY (1) while a previous transfer is
     * still in progress.  Retry up to ~10 ms worth of spin-waits.
     */
    for (int retry = 0; retry < 100; retry++) {
        uint8_t result = CDC_Transmit_FS((uint8_t *)str, len);
        if (result == 0 /* USBD_OK */) return;
        for (volatile int d = 0; d < 10000; d++) { /* ~0.1 ms */ }
    }
}

